"""Declarative schema for the configuration view.

Each entry describes a setting so the UI can render it with a human label,
description and type. This same schema drives the editable "knobs" in the Config tab
AND the allow-list of tunables the read-only AI Advisor is allowed to see — so keep
labels/descriptions user-facing and accurate, and never add secrets/paths here.
"""

CONFIG_SCHEMA = [
    {
        "group": "AI ESS Optimizer",
        "settings": [
            {"key": "AI_POWERED_ESS_ALGORITHM", "label": "AI optimizer enabled", "type": "bool",
             "desc": "Master switch for the AI-powered ESS optimizer."},
            {"key": "WINTER_MODE", "label": "Winter Mode", "type": "bool",
             "desc": "Use the restart-isolated winter optimizer and winter SoC reserve. Off keeps the summer optimizer and summer reserve."},
            {"key": "OPTIMIZER_SLOT_MINUTES", "label": "Planning resolution (min)", "type": "int",
             "desc": "Sub-divides hourly prices into slots of this size; 15 matches quarter-hourly prices."},
            {"key": "OPTIMIZER_SOC_STEP_PCT", "label": "SoC step (%)", "type": "float",
             "desc": "DP discretization step. Smaller = finer control, more compute."},
            {"key": "ESS_TERMINAL_VALUE_FACTOR", "label": "Terminal value factor", "type": "float",
             "desc": "Value of end-of-horizon stored energy on multi-day horizons as a multiple of mean buy price. Same-day-only horizons ignore it so late Tibber prices do not cause evening over-retain."},
            {"key": "ESS_EXPECTED_PEAK_PRICE", "label": "Expected peak price (€/kWh)", "type": "float",
             "desc": "Holds charge for the typical evening/morning peak even before tomorrow's prices publish; 0 disables."},
            {"key": "ESS_MIN_SELL_PRICE", "label": "Min sell price floor (€/kWh)", "type": "float",
             "desc": "Battery is never actively exported below this price (PV surplus still exports freely)."},
            {"key": "ESS_BATTERY_CYCLE_COST", "label": "Battery cycle cost (€/kWh)", "type": "float",
             "desc": "Wear cost per kWh discharged; discourages cycling for marginal arbitrage. 0 disables (not recommended — underprices wear)."},
            {"key": "ESS_ARBITRAGE_MARGIN", "label": "Arbitrage margin (€/kWh)", "type": "float",
             "desc": "Extra profit cushion per kWh discharged (on top of wear) as a forecast-error buffer; prunes thin-spread cycles. 0 disables."},
            {"key": "ESS_MODEL_CHARGE_RATE", "label": "Model full-power charging", "type": "int",
             "desc": "1 = report charging as full-power-to-target (matches reality; accurate BUY settlements); 0 = report the raw DP trajectory. Reporting only — does not change control."},
            {"key": "ESS_SELL_MIN_DWELL_MIN", "label": "SELL hysteresis dwell (min)", "type": "int",
             "desc": "After a sell stops, don't re-enter SELL for this many minutes unless the price has risen enough. Prevents micro-cycling a near-empty battery. 0 disables."},
            {"key": "ESS_SELL_HYSTERESIS_EUR", "label": "SELL hysteresis price rise (€/kWh)", "type": "float",
             "desc": "Within the dwell window, only re-enter SELL if the sell price has risen by at least this much since the last stop."},
        ],
    },
    {
        "group": "Battery & Power Limits",
        "settings": [
            {"key": "BATTERY_CAPACITY_KWH", "label": "Battery capacity (kWh)", "type": "float",
             "desc": "Usable pack capacity used for SoC↔kWh conversions in planning."},
            {"key": "AC_DC_CHARGE_EFFICIENCY", "label": "Charge efficiency", "type": "float",
             "desc": "AC→DC charge efficiency (0–1) used in cost/SoC modelling."},
            {"key": "AC_DC_DISCHARGE_EFFICIENCY", "label": "Discharge efficiency", "type": "float",
             "desc": "DC→AC discharge efficiency (0–1) used for export revenue and the sell floor."},
            {"key": "ESS_MAX_CHARGE_KW", "label": "Max battery charge (kW)", "type": "float",
             "desc": "Upper bound on battery charge power in the optimizer's feasibility checks."},
            {"key": "ESS_MAX_DISCHARGE_KW", "label": "Max battery discharge (kW)", "type": "float",
             "desc": "Upper bound on battery discharge power (set from observed peaks)."},
            {"key": "ESS_MAX_GRID_CHARGE_SOC", "label": "Max grid-charge SoC (%)", "type": "float",
             "desc": "Maximum battery SoC the optimizer may target using grid charging. PV surplus can still charge above this."},
            {"key": "VICTRON_HARDWARE_MIN_SOC", "label": "Victron hardware minimum SoC (%)", "type": "float",
             "desc": "Independent hard MinimumSocLimit. Values above current SoC trigger immediate Victron Recharge; keep 0 to let the optimizer schedule seasonal reserves."},
            {"key": "ESS_MAX_GRID_IMPORT_KW", "label": "Max grid import (kW)", "type": "float",
             "desc": "Grid import limit for the optimizer's feasibility checks."},
            {"key": "ESS_MAX_GRID_EXPORT_KW", "label": "Max grid export (kW)", "type": "float",
             "desc": "Grid export limit for feasibility checks (set from observed peaks)."},
            {"key": "ESS_EXPORT_AC_SETPOINT", "label": "Max export setpoint (W)", "type": "float",
             "desc": "Negative AC power setpoint commanded for a forced SELL (e.g. -13000)."},
            {"key": "MIN_SOC_RESERVE_WINTER", "label": "Winter SoC reserve (%)", "type": "float",
             "desc": "Logical planning floor used when Winter Mode is on; it does not command Victron Recharge."},
            {"key": "MIN_SOC_RESERVE_SUMMER", "label": "Summer SoC reserve (%)", "type": "float",
             "desc": "Logical planning floor used when Winter Mode is off; it does not change Victron's hard minimum."},
        ],
    },
    {
        "group": "Pricing & Forecasts",
        "settings": [
            {"key": "TIBBER_PRICE_RESOLUTION", "label": "Tibber price resolution", "type": "str",
             "options": ["QUARTER_HOURLY", "HOURLY"],
             "desc": "QUARTER_HOURLY (15-min, how Tibber bills) or HOURLY."},
            {"key": "ESS_EXPORT_PRICE_FACTOR", "label": "Export price factor", "type": "float",
             "desc": "sell price = buy × factor − fee."},
            {"key": "ESS_EXPORT_FEE", "label": "Export fee (€/kWh)", "type": "float",
             "desc": "Per-kWh fee subtracted from the export price."},
            {"key": "DAILY_HOME_ENERGY_CONSUMPTION", "label": "Daily consumption (kWh)", "type": "float",
             "desc": "Fallback daily load when the VRM consumption forecast is unavailable."},
            {"key": "ESS_PV_SHAPE_DAYS", "label": "PV shape window (days)", "type": "int",
             "desc": "Trailing days of history used to learn the daylight PV shape that distributes the daily forecast across slots."},
            {"key": "ESS_PV_INTRADAY_CORRECTION", "label": "PV intraday correction", "type": "float",
             "desc": "How strongly to scale the remaining-PV forecast toward realised production when the day runs clearer or cloudier than forecast (0 = off, 1 = full). Applies in both directions."},
            {"key": "ESS_PV_INTRADAY_MAX_RATIO", "label": "PV intraday max ratio", "type": "float",
             "desc": "Cap on the intraday scale-up (e.g. 1.6 = at most +60% vs the VRM day total)."},
            {"key": "ESS_PV_INTRADAY_MIN_RATIO", "label": "PV intraday min ratio", "type": "float",
             "desc": "Floor on the intraday scale-down (e.g. 0.25 = never project the day below 25% of the VRM total, so a passing cloud can't zero it out)."},
            {"key": "ESS_PV_INTRADAY_MIN_ELAPSED", "label": "PV intraday min elapsed", "type": "float",
             "desc": "Fraction of the solar day that must elapse before the UPWARD correction kicks in (avoids noisy early-morning extrapolation)."},
            {"key": "ESS_PV_INTRADAY_DOWN_MIN_ELAPSED", "label": "PV intraday down min elapsed", "type": "float",
             "desc": "Fraction of the solar day that must elapse before the DOWNWARD correction kicks in — held higher than the up threshold so a brief morning cloud that later clears doesn't collapse the day."},
            {"key": "NEGATIVE_PRICE_FEED_IN_LIMIT_ENABLED", "label": "Negative-price feed-in limit", "type": "bool",
             "desc": "Limit grid feed-in to 0W while the price is negative (auto-reverts when it recovers)."},
            {"key": "HISTORY_COMPACTION_ENABLED", "label": "History Parquet compaction", "type": "bool",
             "desc": "Daily (03:20) roll-up of complete past months of history NDJSON into immutable Parquet. Idempotent and safe; needs the duckdb package. Off = keep everything as NDJSON."},
            {"key": "SWITCH_TO_GRID_PRICE_THRESHOLD", "label": "Auto grid-assist price (€/kWh)", "type": "float",
             "desc": "Legacy (non-AI) auto grid-assist: below this price the system covers house load from the grid instead of the battery. Only used when the AI optimizer is off."},
            {"key": "NIGHT_CHARGE_SKIP_ENABLED", "label": "Skip night grid-charge when PV covers tomorrow", "type": "bool",
             "desc": "Skip scheduled overnight grid charging when tomorrow's forecast PV is expected to fill the battery anyway."},
        ],
    },
    {
        "group": "EV Charging & Tesla",
        "settings": [
            {"key": "TESLA_TELEMETRY_ENABLED", "label": "Tesla Fleet Telemetry (push)", "type": "bool",
             "desc": "Read vehicle state from the streamed Fleet Telemetry bridge instead of polling the REST API (no per-read API cost). Off = legacy REST polling. Requires the fleet-telemetry receiver + enrolled vehicle."},
            {"key": "MINIMUM_ESS_SOC", "label": "Minimum ESS SoC for EV surplus (%)", "type": "float",
             "desc": "House-battery SoC that must be reached before exportable PV surplus is offered to the car for solar charging."},
            {"key": "MAXIMUM_ESS_SOC", "label": "Maximum ESS SoC (%)", "type": "float",
             "desc": "Upper SoC bound used by the Victron charge-voltage regulation."},
            {"key": "LOAD_RESERVATION", "label": "House load reservation (W)", "type": "int",
             "desc": "Watts of house load held back from PV before any surplus is offered to the EV (headroom so the house isn't starved)."},
            {"key": "LOAD_REDUCTION_FACTOR", "label": "Load reservation reduction factor", "type": "float",
             "desc": "Divides the load reservation once the house battery reaches its target SoC, freeing more surplus for the car (1 = no reduction)."},
            {"key": "TESLA_POLL_INTERVAL_MIN", "label": "Tesla REST poll — idle (min)", "type": "int",
             "desc": "Legacy REST poll spacing when the car is idle. Ignored in telemetry mode."},
            {"key": "TESLA_POLL_INTERVAL_CHARGING_MIN", "label": "Tesla REST poll — charging (min)", "type": "int",
             "desc": "Legacy REST poll spacing while charging. Ignored in telemetry mode."},
            {"key": "TESLA_POLL_INTERVAL_ASLEEP_MIN", "label": "Tesla REST poll — asleep (min)", "type": "int",
             "desc": "Legacy REST poll backoff when the car is asleep. Ignored in telemetry mode."},
        ],
    },
    {
        "group": "Weather Forecast",
        "settings": [
            {"key": "WEATHER_ENABLED", "label": "Weather forecast enabled", "type": "bool",
             "desc": "Fetch and cache Open-Meteo weather forecasts for shadow-mode forecast analysis."},
            {"key": "HVAC_LOAD_APPLY", "label": "Apply HVAC adjustment", "type": "bool",
             "desc": "When false, compute and log only. Enable only after shadow validation."},
            {"key": "PV_WEATHER_APPLY", "label": "Apply PV weather shape", "type": "bool",
             "desc": "When false, compute and log only. Enable only after shadow validation."},
            {"key": "WEATHER_PROVIDER", "label": "Weather provider", "type": "str",
             "options": ["open-meteo"],
             "desc": "Weather provider id. Open-Meteo is keyless and uses HOME_ADDRESS_LAT/LONG from secrets."},
            {"key": "PV_PANEL_TILT", "label": "PV panel tilt (deg)", "type": "float",
             "desc": "Panel tilt used by Open-Meteo for global tilted irradiance."},
            {"key": "PV_PANEL_AZIMUTH", "label": "PV panel azimuth (deg)", "type": "float",
             "desc": "Panel azimuth used by Open-Meteo for global tilted irradiance."},
            {"key": "WEATHER_FETCH_TTL_MIN", "label": "Weather cache TTL (min)", "type": "int",
             "desc": "Minimum minutes between external forecast refreshes."},
            {"key": "HVAC_LOAD_ENABLED", "label": "HVAC load shadow enabled", "type": "bool",
             "desc": "Compute symmetric heating/cooling degree-day load adjustments in shadow mode."},
            {"key": "HVAC_T_COMFORT_LOW", "label": "HVAC comfort low (C)", "type": "float",
             "desc": "Lower comfort-band edge for heating degree-day load."},
            {"key": "HVAC_T_COMFORT_HIGH", "label": "HVAC comfort high (C)", "type": "float",
             "desc": "Upper comfort-band edge for cooling degree-day load."},
            {"key": "HVAC_ALPHA_COOL", "label": "Cooling alpha (kWh/DD)", "type": "float",
             "desc": "Shadow-mode cooling load coefficient, kWh per cooling degree-day."},
            {"key": "HVAC_ALPHA_HEAT", "label": "Heating alpha (kWh/DD)", "type": "float",
             "desc": "Shadow-mode heating load coefficient, kWh per heating degree-day."},
            {"key": "HVAC_LOAD_MAX_DELTA_KWH", "label": "HVAC max load delta (kWh)", "type": "float",
             "desc": "Daily safety cap for weather-derived load adjustment."},
            {"key": "PV_WEATHER_ENABLED", "label": "PV weather shadow enabled", "type": "bool",
             "desc": "Compute GTI-shaped PV shadow forecasts while preserving VRM daily magnitude."},
            {"key": "PV_WEATHER_BLEND", "label": "PV weather blend", "type": "float",
             "desc": "Blend weight between VRM PV shape and GTI-derived PV shape."},
        ],
    },
    {
        "group": "AI Advisor",
        "settings": [
            {"key": "ADVISOR_AUTH", "label": "Advisor auth mode", "type": "str",
             "options": ["auto", "cli", "api"],
             "desc": "How the read-only advisor authenticates. auto prefers CLI subscription login when available."},
            {"key": "ADVISOR_MODEL", "label": "Advisor model", "type": "str",
             "desc": "Optional model override for the advisor runner. Leave blank for the provider default."},
            {"key": "ADVISOR_HISTORY_DAYS", "label": "Advisor history days", "type": "int",
             "desc": "Trailing days included inline in advisor prompts before on-demand retrieval is used."},
            {"key": "ADVISOR_MAX_THINKING_TOKENS", "label": "Advisor thinking token cap", "type": "int",
             "desc": "Bounded extended-thinking budget for capable CLI models. 0 disables it."},
            {"key": "ADVISOR_MAX_INPUT_CHARS", "label": "Advisor input char cap", "type": "int",
             "desc": "Hard cap for prompt size; history detail is trimmed to fit."},
            {"key": "ADVISOR_RETRIEVAL_MAX_DAYS", "label": "Advisor retrieval days", "type": "int",
             "desc": "Maximum extra history days one open-ended question may retrieve."},
            {"key": "ADVISOR_RETRIEVAL_MAX_CHARS", "label": "Advisor retrieval char cap", "type": "int",
             "desc": "Maximum extra history payload injected after on-demand retrieval."},
        ],
    },
]

_NUMERIC_BOUNDS = {
    "OPTIMIZER_SLOT_MINUTES": (5, 60),
    "OPTIMIZER_SOC_STEP_PCT": (0.25, 10),
    "ESS_TERMINAL_VALUE_FACTOR": (0, 5),
    "ESS_EXPECTED_PEAK_PRICE": (0, 2),
    "ESS_MIN_SELL_PRICE": (0, 2),
    "ESS_BATTERY_CYCLE_COST": (0, 1),
    "ESS_ARBITRAGE_MARGIN": (0, 1),
    "ESS_MODEL_CHARGE_RATE": (0, 1),
    "ESS_SELL_MIN_DWELL_MIN": (0, 240),
    "ESS_SELL_HYSTERESIS_EUR": (0, 1),
    "BATTERY_CAPACITY_KWH": (1, 200),
    "AC_DC_CHARGE_EFFICIENCY": (0.1, 1),
    "AC_DC_DISCHARGE_EFFICIENCY": (0.1, 1),
    "ESS_MAX_CHARGE_KW": (0, 50),
    "ESS_MAX_DISCHARGE_KW": (0, 50),
    "ESS_MAX_GRID_CHARGE_SOC": (0, 100),
    "ESS_MAX_GRID_IMPORT_KW": (0, 50),
    "ESS_MAX_GRID_EXPORT_KW": (0, 50),
    "ESS_EXPORT_AC_SETPOINT": (-50000, 0),
    "MIN_SOC_RESERVE_WINTER": (0, 100),
    "MIN_SOC_RESERVE_SUMMER": (0, 100),
    "VICTRON_HARDWARE_MIN_SOC": (0, 100),
    "ESS_EXPORT_PRICE_FACTOR": (0, 2),
    "ESS_EXPORT_FEE": (0, 1),
    "DAILY_HOME_ENERGY_CONSUMPTION": (0, 200),
    "ESS_PV_SHAPE_DAYS": (1, 60),
    "ESS_PV_INTRADAY_CORRECTION": (0, 1),
    "ESS_PV_INTRADAY_MAX_RATIO": (1, 5),
    "ESS_PV_INTRADAY_MIN_RATIO": (0, 1),
    "ESS_PV_INTRADAY_MIN_ELAPSED": (0, 1),
    "ESS_PV_INTRADAY_DOWN_MIN_ELAPSED": (0, 1),
    "PV_PANEL_TILT": (0, 90),
    "PV_PANEL_AZIMUTH": (0, 360),
    "WEATHER_FETCH_TTL_MIN": (1, 1440),
    "HVAC_T_COMFORT_LOW": (-30, 50),
    "HVAC_T_COMFORT_HIGH": (-30, 50),
    "HVAC_ALPHA_COOL": (0, 20),
    "HVAC_ALPHA_HEAT": (0, 20),
    "HVAC_LOAD_MAX_DELTA_KWH": (0, 100),
    "PV_WEATHER_BLEND": (0, 1),
    "ADVISOR_HISTORY_DAYS": (1, 30),
    "ADVISOR_MAX_THINKING_TOKENS": (0, 200000),
    "ADVISOR_MAX_INPUT_CHARS": (1000, 1000000),
    "ADVISOR_RETRIEVAL_MAX_DAYS": (1, 90),
    "ADVISOR_RETRIEVAL_MAX_CHARS": (1000, 1000000),
    "SWITCH_TO_GRID_PRICE_THRESHOLD": (0, 2),
    "MINIMUM_ESS_SOC": (0, 100),
    "MAXIMUM_ESS_SOC": (0, 100),
    "LOAD_RESERVATION": (0, 20000),
    "LOAD_REDUCTION_FACTOR": (1, 10),
    "TESLA_POLL_INTERVAL_MIN": (1, 240),
    "TESLA_POLL_INTERVAL_CHARGING_MIN": (1, 240),
    "TESLA_POLL_INTERVAL_ASLEEP_MIN": (1, 1440),
}

for _group in CONFIG_SCHEMA:
    for _setting in _group["settings"]:
        if _setting.get("type") in ("int", "float"):
            _setting["min"], _setting["max"] = _NUMERIC_BOUNDS[_setting["key"]]
