"""Declarative schema for the configuration view.

Each entry describes a setting so the UI can render it with a human label,
description and type. This same schema drives the editable "knobs" in the Config tab
AND the allow-list of tunables the read-only AI Advisor is allowed to see — so keep
labels/descriptions user-facing and accurate, and never add secrets/paths here.
"""

CONFIG_SCHEMA = [
    {
        "group": "AI ESS Optimizer",
        "settings": [
            {"key": "AI_POWERED_ESS_ALGORITHM", "label": "AI optimizer enabled", "type": "bool",
             "desc": "Master switch for the AI-powered ESS optimizer."},
            {"key": "OPTIMIZER_SLOT_MINUTES", "label": "Planning resolution (min)", "type": "int",
             "desc": "Sub-divides hourly prices into slots of this size; 15 matches quarter-hourly prices."},
            {"key": "OPTIMIZER_SOC_STEP_PCT", "label": "SoC step (%)", "type": "float",
             "desc": "DP discretization step. Smaller = finer control, more compute."},
            {"key": "ESS_TERMINAL_VALUE_FACTOR", "label": "Terminal value factor", "type": "float",
             "desc": "Value of end-of-horizon stored energy as a multiple of the horizon mean buy price. Keep near 1.0; >1 risks hoarding/under-selling."},
            {"key": "ESS_EXPECTED_PEAK_PRICE", "label": "Expected peak price (€/kWh)", "type": "float",
             "desc": "Holds charge for the typical evening/morning peak even before tomorrow's prices publish; 0 disables."},
            {"key": "ESS_MIN_SELL_PRICE", "label": "Min sell price floor (€/kWh)", "type": "float",
             "desc": "Battery is never actively exported below this price (PV surplus still exports freely)."},
            {"key": "ESS_BATTERY_CYCLE_COST", "label": "Battery cycle cost (€/kWh)", "type": "float",
             "desc": "Wear cost per kWh discharged; discourages cycling for marginal arbitrage. 0 disables (not recommended — underprices wear)."},
            {"key": "ESS_ARBITRAGE_MARGIN", "label": "Arbitrage margin (€/kWh)", "type": "float",
             "desc": "Extra profit cushion per kWh discharged (on top of wear) as a forecast-error buffer; prunes thin-spread cycles. 0 disables."},
            {"key": "ESS_MAX_GRID_CHARGE_PRICE", "label": "Max grid-charge price (€/kWh)", "type": "float",
             "desc": "Only grid-charge when the buy price is at/below this (PV charging is never gated). 0 disables."},
            {"key": "ESS_GRID_CHARGE_CHEAP_PCT", "label": "Grid-charge cheap %", "type": "float",
             "desc": "Only grid-charge when the price is in the cheapest N% of the horizon. 0 or >=100 disables."},
            {"key": "ESS_MODEL_CHARGE_RATE", "label": "Model full-power charging", "type": "int",
             "desc": "1 = report charging as full-power-to-target (matches reality; accurate BUY settlements); 0 = report the raw DP trajectory. Reporting only — does not change control."},
            {"key": "ESS_SELL_MIN_DWELL_MIN", "label": "SELL hysteresis dwell (min)", "type": "int",
             "desc": "After a sell stops, don't re-enter SELL for this many minutes unless the price has risen enough. Prevents micro-cycling a near-empty battery. 0 disables."},
            {"key": "ESS_SELL_HYSTERESIS_EUR", "label": "SELL hysteresis price rise (€/kWh)", "type": "float",
             "desc": "Within the dwell window, only re-enter SELL if the sell price has risen by at least this much since the last stop."},
        ],
    },
    {
        "group": "Battery & Power Limits",
        "settings": [
            {"key": "BATTERY_CAPACITY_KWH", "label": "Battery capacity (kWh)", "type": "float",
             "desc": "Usable pack capacity used for SoC↔kWh conversions in planning."},
            {"key": "AC_DC_CHARGE_EFFICIENCY", "label": "Charge efficiency", "type": "float",
             "desc": "AC→DC charge efficiency (0–1) used in cost/SoC modelling."},
            {"key": "AC_DC_DISCHARGE_EFFICIENCY", "label": "Discharge efficiency", "type": "float",
             "desc": "DC→AC discharge efficiency (0–1) used for export revenue and the sell floor."},
            {"key": "ESS_MAX_CHARGE_KW", "label": "Max battery charge (kW)", "type": "float",
             "desc": "Upper bound on battery charge power in the optimizer's feasibility checks."},
            {"key": "ESS_MAX_DISCHARGE_KW", "label": "Max battery discharge (kW)", "type": "float",
             "desc": "Upper bound on battery discharge power (set from observed peaks)."},
            {"key": "ESS_MAX_GRID_IMPORT_KW", "label": "Max grid import (kW)", "type": "float",
             "desc": "Grid import limit for the optimizer's feasibility checks."},
            {"key": "ESS_MAX_GRID_EXPORT_KW", "label": "Max grid export (kW)", "type": "float",
             "desc": "Grid export limit for feasibility checks (set from observed peaks)."},
            {"key": "ESS_EXPORT_AC_SETPOINT", "label": "Max export setpoint (W)", "type": "float",
             "desc": "Negative AC power setpoint commanded for a forced SELL (e.g. -13000)."},
            {"key": "MIN_SOC_RESERVE_WINTER", "label": "Winter SoC reserve (%)", "type": "float",
             "desc": "Minimum SoC the optimizer keeps in winter months."},
            {"key": "MIN_SOC_RESERVE_SUMMER", "label": "Summer SoC reserve (%)", "type": "float",
             "desc": "Minimum SoC the optimizer keeps in summer months (the BMS still enforces its own bottom buffer; 0 is a valid floor)."},
        ],
    },
    {
        "group": "Pricing & Forecasts",
        "settings": [
            {"key": "TIBBER_PRICE_RESOLUTION", "label": "Tibber price resolution", "type": "str",
             "options": ["QUARTER_HOURLY", "HOURLY"],
             "desc": "QUARTER_HOURLY (15-min, how Tibber bills) or HOURLY."},
            {"key": "ESS_EXPORT_PRICE_FACTOR", "label": "Export price factor", "type": "float",
             "desc": "sell price = buy × factor − fee."},
            {"key": "ESS_EXPORT_FEE", "label": "Export fee (€/kWh)", "type": "float",
             "desc": "Per-kWh fee subtracted from the export price."},
            {"key": "DAILY_HOME_ENERGY_CONSUMPTION", "label": "Daily consumption (kWh)", "type": "float",
             "desc": "Fallback daily load when the VRM consumption forecast is unavailable."},
            {"key": "ESS_PV_SHAPE_DAYS", "label": "PV shape window (days)", "type": "int",
             "desc": "Trailing days of history used to learn the daylight PV shape that distributes the daily forecast across slots."},
            {"key": "ESS_PV_INTRADAY_CORRECTION", "label": "PV intraday correction", "type": "float",
             "desc": "How strongly to scale the remaining-PV forecast UP toward realised production on a better-than-forecast day (0 = off, 1 = full). Only ever raises the forecast."},
            {"key": "ESS_PV_INTRADAY_MAX_RATIO", "label": "PV intraday max ratio", "type": "float",
             "desc": "Cap on the intraday scale-up (e.g. 1.6 = at most +60%)."},
            {"key": "ESS_PV_INTRADAY_MIN_ELAPSED", "label": "PV intraday min elapsed", "type": "float",
             "desc": "Fraction of the solar day that must elapse before intraday correction kicks in (avoids noisy early-morning extrapolation)."},
            {"key": "NEGATIVE_PRICE_FEED_IN_LIMIT_ENABLED", "label": "Negative-price feed-in limit", "type": "bool",
             "desc": "Limit grid feed-in to 0W while the price is negative (auto-reverts when it recovers)."},
        ],
    },
]
