name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build_and_push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Create CalVer tag
        id: calver
        run: |
          echo "TAG=$(date +%Y.%m.%d)" >> $GITHUB_ENV

      - name: Debug Info
        run: |
          whoami
          id
          echo "Next version will be: ${{ env.TAG }}"          

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Multi and push to CR
        uses: docker/build-push-action@v3
        env:
          tag: ${{ env.TAG }}
        with:
          file: cerbomoticzGx.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/joshuadodds/cerbomoticzgx:2022.11.26.0
