name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:
  
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.2
      
      - name: Debug Info
        run: |
         whoami
         id
         sudo docker info
         
      - name: Build Multi
        uses: docker/build-push-action@v2.4.0
        with:
         file: cerbomoticzGx.Dockerfile
         platforms: linux/amd64,linux/arm64
