name: CI Workflow

on:
  push:
    tags:
      - '*'
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_and_push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Create CalVer tag
        id: calver
        run: |
          echo "tag=$(TZ='Europe/Amsterdam' date +%Y.%m.%d.%H)" >> $GITHUB_OUTPUT
          echo "repo=$(echo ${{ github.repository }} | tr [:upper:] [:lower:])" >> $GITHUB_OUTPUT

      - name: Debug Info
        run: |
          whoami
          id
          echo "Next version will be: ${{ steps.calver.outputs.tag }}"          

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Multi and push to CR
        uses: docker/build-push-action@v3
        with:
          file: cerbomoticzGx.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.calver.outputs.repo }}:${{ steps.calver.outputs.tag }}
            ghcr.io/${{ steps.calver.outputs.repo }}:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.calver.outputs.repo }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ steps.calver.outputs.repo }}:buildcache,mode=max
